### ISSUE TITLE
Ability to change EBS volume type

### ISSUE THREAD

**Issue by snamburi3** [aws/amazon-genomics-cli#218]
**Description**
Most of the genomics jobs do not need a SSD volume. Presently General Purpose SSD (gp3) - Storage is attached by default. We could use Throughput Optimized HDD (st1) Volumes to save costs. We need ability to change the volume type of the disk according to the workflow.

**Proposed Solution**
When deploying the context, provide data volume type.

**Comment by markjschreiber** [comment]
The `gp3` disks were selected because at scale docker can experience problems with not being able to start several containers on a single host at the same time due to throughput. In the case of the Cromwell and Nextflow engines the scratch space for each task is actually inside the container which means all work is happening on the mount used by docker and hence is `gp3`. There would be a fairly significant amount of re-engineering required to change how both of those engines currently use AWS Batch.
