### ISSUE TITLE
AGC thinks a WDL `Log` object's `exit_code` should be a string, but the spec defines it as an integer

### ISSUE THREAD

**Issue by adamnovak** [aws/amazon-genomics-cli#314]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)

I reported this as https://github.com/DataBiosphere/toil/issues/4030, but according to [the spec](https://github.com/ga4gh/workflow-execution-service-schemas/blob/c3b19854240c4fcbaf3483e22b19db0a918a7ee5/openapi/workflow_execution_service.swagger.yaml#L409-L412) I think Toil is right to send an integer here and AGC is wrong to require a string.

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

1. Use AGC with Toil engine: https://github.com/adamnovak/amazon-genomics-cli/commit/d831ee9c346a545ea63b11a82da26b3cc8ccecad
2. Set up a Toil engine Docker container for Toil https://github.com/DataBiosphere/toil/commit/fc8e0e2d63ed5d2db609654ddd6a0c3e86d8144f, using the Toil Dockerfile in AGC, and put it in ECR.
3. Set up a Toil engine context using the CWL demo context that uses Toil
4. Run a workflow
5. Retrieve the workflow logs with `agc workflow output`

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)

```
2022-02-01T15:17:07-08:00 ✘   error="json: cannot unmarshal number into Go struct field Log.run_log.exit_code of type string"
Error: an error occurred invoking 'workflow output'
with variables: {runId:b4b54c271ab1453f88c7912cf8c757b9}
caused by: json: cannot unmarshal number into Go struct field Log.run_log.exit_code of type string
```

**Expected Behavior**

[//]: #  (A clear and concise description of what you expected to happen.)

AGC should be able to unmarshall a run log exit code that comes in as an unquoted integer, as the spec defines it as an integer.

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)

AGC fails at deserialization unless the exit code is quoted as a string in the WES JSON response.

**Screenshots**

[//]: #  (If applicable, add screenshots to help explain your problem.)

N/A

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System: Fedora
AGC Version: d831ee9c346a545ea63b11a82da26b3cc8ccecad
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

**Comment by adamnovak** [comment]
Part of the issue here might be that this is for the Log object provided as `run_log` for the `GetRunLog` call; the `task_logs` Log objects might have different behavior, and I'm not sure AGC WES adapters ever send `run_log` with an exit code.

**Comment by a-li** [comment]
You are correct. We did recently change the exit code handling from WES and converted it from an `int` to a `string` (as part of #276) as we started seeing some failing tasks not having an exit/return code so it defaulted to 0 which was a bit misleading.

I have seen that issue before when I was making the changes. Just to double check and could you go to `packages/cli` directory and run `go mod vendor`. The vendor files are not committed to GitHub and there's a good chance it's still using the cache version which is referring the number type when building locally. 

Another thing to check while you're still using the same version, can you run a `agc logs workflow` and does that output anything?

**Comment by nbraid** [comment]
I think the concern is that by changing it from an `int` to a `string`, we're technically violating the [WES spec](https://github.com/aws/amazon-genomics-cli/blob/main/packages/wes_api/client/api/openapi.yaml#L387-L390). The Toil WES implementation, if it adheres to the spec, would return an `int` which AGC is now rejecting. Perhaps we should go back to returning a non-required `int` from WES and handling the conversion of a missing `int` to an empty string in the console within AGC.

I suspect we made this change because the exitCode is possibly-null in the JSON returned by the server, but when deserialized as an `int` the generated [WES client](https://github.com/aws/amazon-genomics-cli/commit/3c6173525b6e1b991c9ba52258822ad37fb024bc#diff-52dd1c0845070f917ab32b5b0bafdc8e0bd24548227ff542303f6be0c0cd3d2e), a null value defaults to `0`. 

We could instead replace this with a zero value, e.g. return an exit code of -1 if no exit code is returned from the source. This would make us _technically_ compliant with the spec, but could be confusing, as the intuitive thing to do when you have no value for an optional response field would be not to return one. This means we could get back into the same situation if a future engine implementer doesn't know about this quirk and we start getting zero-by-default behavior again.

A better solution might be to use something like https://github.com/volatiletech/null (or a similar implementation) in the WES client to accurately capture the concept that the server is returning, but does not exist in Go: a nillable int.

Then when we go to display the exit code in the console, we can display an empty string if the `exitCode == nil`

**Comment by adamnovak** [comment]
What I need is for the deserialization code to accept an unquoted JSON int, if the key is present. It's fine for the internal format to stay a string to allow a missing value to be represented, and for the adapters to keep sending a quoted string, as long as the unmarshalling code can also tolerate an unquoted number.
