### ISSUE TITLE
Multiple workflows 

### ISSUE THREAD

**Issue by divyaravindran03** [aws/amazon-genomics-cli#411]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

Can I use AGC to run multiple workloads ( Example - Single wdl and different input json files )?

**Use Case**

We need to run same workflow with different inputs .

**Proposed Solution**
In MANIFEST.json can we give like this ?
{
  "mainWorkflowURL": "xxx_processing_aws_agc.wdl",
  "inputFileURLs": [
    "xxxx_xxxx_test_aws1.json",
    "xxxx_xxxx_test_aws2.json"
    "xxxx_xxxx_test_aws3.json"
  ]
}

**Other information**

Is there a way to do it ?

**Comment by wleepang** [comment]
@divyaravindran03

When using AGC with Cromwell, the list in MANIFEST/inputFiles is passed to Cromwell as workflowInput.json, workflowInput_1.json, … , workflowInput_5.json. If all the files have the same structure, then the values in higher numbered files will take precedence.

We previously updated the documentation to make this clearer with the following pull-request, but it looks like the change was accidentally reverted.
https://github.com/aws/amazon-genomics-cli/pull/350

Otherwise, I've seen a few users script `agc workflow run`, dynamically generating a MANIFEST for each submission to accomplish what you need.

**Comment by divyaravindran03** [comment]
Thanks .Let me try to execute multiple test cases  . Through Scripts I could execute multiple testcase sequentially and Parallely. Currently is there a way in tool where we can submit more jobs and execute it parallelly(MultiThreading/MultiProcessing) ,With workflowId's we would be able to differentiate logs too.

**Comment by wleepang** [comment]
Submitting workflows is an asynchronous operation. Multiple workflows can be submitted in rapid succession and effectively run in parallel. The Amazon Genomics CLI doesn't have any persistent local compute process, but rather communicates with cloud resources via GA4GH API requests.
