### ISSUE TITLE
docker ulimits

### ISSUE THREAD

**Issue by JeffBurdine** [aws/amazon-genomics-cli#45]
Question:
Some of our nextflow pipelines end up hitting nofile ulimit issues within docker.  In order to avoid this when utilizing the former aws templates we would add the following to the provision.sh script.
`# common provisioning for all workflow orchestrators
cd /opt
sh $BASEDIR/ecs-additions-common.sh
sed -i 's/nofile=.*/nofile=65536:65536"/' /etc/sysconfig/docker`

can this be set in a context?
Related issue here
https://github.com/aws-samples/aws-genomics-workflows/issues/150

**Comment by markjschreiber** [comment]
In that case the best strategy here would be to have Nextflow request a higher limit when requesting the run. See the `ulimits` section of https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#containerProperties

If Nextflow cannot do this it would be worth raising a ticket with them as the problem is much more generic than just AGC.

**Comment by markjschreiber** [comment]
As a work around, if you clone the repository you could specify the limit in the LaunchTemplate. The content of the LaunchTemplate is in https://github.com/aws/amazon-genomics-cli/blob/main/packages/cdk/lib/constants.ts#L11-L106

I don't think changing it here should be a long term fix though.

**Comment by eddie1183** [comment]
As @markjschreiber suggested it may be worth cutting a ticket to next flow to increase the limit when requesting a run. Closing the issue due to inactivity.
